### ISSUE TITLE
Wouldn't gettext integration be a good idea?

### ISSUE THREAD

**Issue by oliverandrich** [aaronrenner/phx_gen_auth#104]
Is there be any downside, if phx_gen_auth would directly use gettext? All my current projects have to support English and German and in all of them I added i18n manually after running "mix phx.gen.auth".

**Comment by josevalim** [comment]
It is something you can add manually, we keep the amount of markup to a minimum so it is not that much work. The reason we don't do it by default is that then everyone would have to remove it, if they don't need it, and I assume most people don't actually need it, and an option would be too complex.

**Comment by oliverandrich** [comment]
Thanks for the quick response. From a very English minded view, you are absolutely correct. I have to review my process because currently, I have to do about 40 manual changes in templates, controllers and so on. And I tend to forget locations. ;)

**Comment by josevalim** [comment]
It is not even about English per se. If I am doing a website in portuguese, I would simply rewrite the english to portuguese but without using gettext. :)
