### ISSUE TITLE
Is assign(:token, token) in get_user_by_reset_password_token(conn, _opts) used for?

### ISSUE THREAD

**Issue by manhtranlinh** [aaronrenner/phx_gen_auth#113]
Hi all,
In the plug :get_user_by_reset_password_token 
`
 defp get_user_by_reset_password_token(conn, _opts) do
    %{"token" => token} = conn.params

    if user = Accounts.get_user_by_reset_password_token(token) do
      conn |> assign(:user, user) |> assign(:token, token) 
    else
      conn
      |> put_flash(:error, "Reset password link is invalid or it has expired.")
      |> redirect(to: "/")
      |> halt()
    end
  end'
I can not find where is used assign(:token, token), I tried remove it the program work the same.
Could you please tell me if any case we can use it or that is a preparation for next feature in future time.
Thanks and Best Regards.

**Comment by aaronrenner** [comment]
Hi @manhtranlinh! This assigns is referenced in the `user_reset_password/edit.html.eex` template when calling the `Routes.user_reset_password_path/3` helper (`@token`).

https://github.com/aaronrenner/phx_gen_auth_output/blob/6a2d9e223ec1d90d6d6b79103f5d07944f4b2993/lib/demo_web/templates/user_reset_password/edit.html.eex#L3

By having the token in the path for the edit and update actions, we're able to look up the user whose password we're trying to reset.

I hope this helps!
