### ISSUE TITLE
Two elements with non-unique id #user_action

### ISSUE THREAD

**Issue by dbi1** [aaronrenner/phx_gen_auth#120]
On the phx.gen.auth settings page, I get the following notice in the Chrome Dev Tools console:

`[DOM] Found 2 elements with non-unique id #user_action: (More info: https://goo.gl/9p2vKq) <input id=​"user_action" name=​"action" type=​"hidden" value=​"update_email">​ <input id=​"user_action" name=​"action" type=​"hidden" value=​"update_password">​`

Just wanted to pass this along.

P.S.: The phx.gen.auth code is a delight to follow (even for a less experienced developer like myself), as it is highly readable. Really nice :) Thanks for the great work on phx.gen.auth!

**Comment by josevalim** [comment]
Please see: https://github.com/phoenixframework/phoenix/pull/4420
