### ISSUE TITLE
Add an option to generate auth with username instead of email

### ISSUE THREAD

**Issue by nskins** [aaronrenner/phx_gen_auth#125]
It would be nice to have a custom option for applications that don't need a user's email address to have the authentication generated with a username instead. This means the register and login screens would only require a username (with some minimum length) and a password.

I often work on projects that I like to show my friends and the open source community, but I don't want to deter someone away because they need to provide an email.

**Comment by josevalim** [comment]
We don’t plan to add more options and flags, as it comes with complexity on the generator, the goal is for you to change and extended the generated code as needed.
