### ISSUE TITLE
Confirmation routes can confirm changes without user acknowledgement

### ISSUE THREAD

**Issue by liamwhite** [aaronrenner/phx_gen_auth#126]
The other controllers require some sort of POST interaction, but the [confirmation](https://github.com/aaronrenner/phx_gen_auth/blob/a9e92df94afb8eef8dae0a41a9c1654863607874/priv/templates/phx.gen.auth/routes.ex#L31) and [email confirmation](https://github.com/aaronrenner/phx_gen_auth/blob/a9e92df94afb8eef8dae0a41a9c1654863607874/priv/templates/phx.gen.auth/routes.ex#L22) routes are GET only, and therefore can be triggered by automatic link fetchers in popular email providers. This allows accounts/emails to be confirmed as long as such an email address is known to exist:
https://support.google.com/mail/thread/16878288/gmail-is-opening-and-caching-urls-within-emails-without-user-intervention-how-and-why?hl=en

**Comment by josevalim** [comment]
Good call, I will make it two steps. :)

**Comment by josevalim** [comment]
Please see: https://github.com/phoenixframework/phoenix/pull/4419
