### ISSUE TITLE
Scoping paths in Router

### ISSUE THREAD

**Issue by Kaquadu** [aaronrenner/phx_gen_auth#127]
Hello,
I've got a question about paths generated in the Router. Is this intended that these paths are not scoped under the name of the user's schema? If yes - why is that? I know that it is an easy change and it takes 30 seconds to rename the scope, but I am just curious what is the reason.

My point is that according to the Phoenix documentation scopes are a way to group routes under a common path prefix and scoped set of plugs. In this case all paths use the same prefix, which is `<%= schema.plural %>`.

https://github.com/aaronrenner/phx_gen_auth/blob/master/priv/templates/phx.gen.auth/routes.ex

**Comment by aaronrenner** [comment]
Hi @Kaquadu. If you don't mind, would you open this issue under the phoenix repo? Now that this has been merged into phoenix 1.6, I'm archiving this repository.
