### ISSUE TITLE
Can "maybe_hash_password" run the "else" condition?

### ISSUE THREAD

**Issue by dalarenal** [aaronrenner/phx_gen_auth#14]
I've used this in my project, and I noticed that the coverage of tests is not 100%. Checking the code, the part without test is this one, in the `else` condition:
https://github.com/aaronrenner/phx_gen_auth/blob/v0.2.0/priv/templates/phx.gen.auth/schema.ex#L52
```elixir
 defp maybe_hash_password(changeset) do
    if password = get_change(changeset, :password) do
      changeset
      |> put_change(:hashed_password, <%= inspect hashing_library.module %>.hash_pwd_salt(password))
      |> delete_change(:password)
    else
      changeset
    end
  end
```

I've been trying to identify in which cases we can reach that `else`. It only happens in the registration and password changesets. For both, you need to enter the password, so the `if` condition will be true (as this will run only if is valid, durint the `Repo.insert`.

Could this be simplified without the `if else`, or I'm I missing something? Or in the case there is a way to reach it, could that be added to the tests?

**Comment by josevalim** [comment]
Currently it cannot but I think that as soon as you add other fields and you want to update them alongside your password, then it will be triggered.

**Comment by dalarenal** [comment]
I think as it is in [`prepare_changes`](https://github.com/aaronrenner/phx_gen_auth/blob/v0.2.0/priv/templates/phx.gen.auth/schema.ex#L48), it can be triggered only when the changeset is valid. To be valid, it [requires the password](https://github.com/aaronrenner/phx_gen_auth/blob/v0.2.0/priv/templates/phx.gen.auth/schema.ex#L43).

Then, if everytime `maybe_hash_password` receives a changeset with the password, `if password = get_change(changeset, :password) do` will return it, and the `else` condition can't be triggered, even you add more fields.

**Comment by josevalim** [comment]
Ah, yes. Since we also have validate_required, you are correct. I will also change it in the original project, thanks!

**Comment by josevalim** [comment]
I have fixed it on the original repo. Feel free to send a PR here too. :)
