### ISSUE TITLE
Bump required phoenix dependency to 1.5.2

### ISSUE THREAD

**Issue by aaronrenner** [aaronrenner/phx_gen_auth#17]
Need to bump dependency once phoenix 1.5.2 is released, due to this commit:

https://github.com/dashbitco/mix_phx_gen_auth_demo/pull/1/commits/4113391098d5bf1c562bb9e87d7e32a6f261b342

**Comment by aaronrenner** [comment]
@josevalim I'm waiting to release v0.3.0 until phoenix 1.5.2 is released, since it undeprecates `Endpoint.subscribe/1`. Since there have been several of changes to the generated code in the past few weeks, I'm considering rolling back this commit (https://github.com/dashbitco/mix_phx_gen_auth_demo/commit/4113391098d5bf1c562bb9e87d7e32a6f261b342) and doing an interim release. However, if 1.5.2 is going to be released soon that wouldn't make much sense. Do you have any guidance here and do I even need to wait until 1.5.2 is released to publish a version that calls `MyApp.Enpoint.subscribe/1`?

**Comment by josevalim** [comment]
That works, although i think the plan is to release v1.5.2 this week. Both ways work tho!

**Comment by aaronrenner** [comment]
Oh, awesome! Thanks for the info. By the time I'm finished making the rest of the updates I need, I bet 1.5.2 will be out.
