### ISSUE TITLE
Generator injection issue (plug :fetch_current_user)

### ISSUE THREAD

**Issue by woylie** [aaronrenner/phx_gen_auth#22]
I just ran the generator in an existing project. Before, my browser pipeline in the router looked like this:

```elixir
pipeline :browser do
    ...
    plug :put_secure_browser_headers, %{"content-security-policy" => @csp}
end
```

The generator put the options for `put_secure_browser_headers` behind `fetch_current_user`:

```elixir
pipeline :browser do
    ...
    plug :put_secure_browser_headers
    plug :fetch_current_user, %{"content-security-policy" => @csp}
 end
```

**Comment by aaronrenner** [comment]
Thanks for reporting this! I just pushed a fix to master.
