### ISSUE TITLE
Clean expired tokens?

### ISSUE THREAD

**Issue by thojanssens** [aaronrenner/phx_gen_auth#23]
Hello, user session tokens are being piled up in the "users_tokens" table. I don't see any code that cleans up expired tokens. There is also no `:expired_at` field.

An app may have a lot of new sessions every day, this table can lead to very high number of records in a relatively short time.

I do not see reasons why not provide a mechanism to clean this up, as every developer will lead to plus or less the same code doing that.

**Comment by thojanssens** [comment]
I see the session is cleared on logout:
```
def delete(conn, _params) do
  conn
  |> put_flash(:info, "Logged out successfully.")
  |> UserAuth.logout_user()
end
```

```
def delete_session_token(token) do
  Repo.delete_all(UserToken.token_and_context_query(token, "session"))
  :ok
end
```

But that implies that the user triggers the logout. I believe most users just leave the site. Tokens can expire. Then there's no deletion mechanism for those expired tokens.

**Comment by josevalim** [comment]
You can add your own logic to expire tokens. No token lasts more than 60 days, so you can build something off that.

**Comment by thojanssens** [comment]
I think this may be included except if there are really too many ways to achieve this; because everyone will have to code it, it seems a must to me. A small periodical task to remove tokens older than 60 days, that developers can customize. To me, the argument not to would be that we can leave the tokens in the table (not my opinion), or that it is too application-specific (not my opinion).

Is just a suggestion:) I'll add my own logic now.
(Btw can't thank enough for this amazing work, I really love the authentication system and this is one more  selling point for going with Phoenix.)
