### ISSUE TITLE
Use `__MODULE__` when possible?

### ISSUE THREAD

**Issue by thojanssens** [aaronrenner/phx_gen_auth#25]
I see in the code that we prefer to generate the full module name when that name references the module we're in. Any reason to not prefer the usage of `__MODULE__`?

A good example is the xxxToken module and the numerous use of:
```
<%= inspect schema.module %>Token
```

The advantage of `__MODULE__` is that the module is easier to rename. I don't see disadvantages in its use.

**Comment by josevalim** [comment]
Hi @thojanssens, I personally find `UserToken` easier to read than `__MODULE__`. We all have preferences in terms of code and it is impossible that the generators will please all of us.

**Comment by thojanssens** [comment]
Of course:) thank you
