### ISSUE TITLE
Use Router helpers in test cases assertions

### ISSUE THREAD

**Issue by chvanikoff** [aaronrenner/phx_gen_auth#40]
Hi,
I'd suggest changing generated test cases to assert against `Routes.*_path` rather than plain string - this way it becomes much easier to change routes like `/users/login` -> `/auth/login`.
i.e.:
```diff
- assert redirected_to(conn) == "/users/login"
+ assert redirected_to(conn) == Routes.user_session_path(conn, :new)
```

**Comment by josevalim** [comment]
I agree. A PR is welcome!
