### ISSUE TITLE
User or Credential? Rewrite the Authentication part of the Phoenix Guides

### ISSUE THREAD

**Issue by joepstender** [aaronrenner/phx_gen_auth#56]
The Phoenix Guides use a slightly different but, when put against what phx_gen_auth produces, utterly confusing naming regarding authentication. In the Phoenix Guides "Credential" is used instead of "User", and they use it as an example how to created a one_to_one relationship: 
`mix phx.gen.context Accounts Credential credentials email:string:unique user_id:references:users`

One or the other will have to yield If you want to merge to Phoenix. Either way the Authentication part of the Phoenix Guides should be rewritten.

**Comment by josevalim** [comment]
Yes. It is not related to this project per se but it is in our plans to rewrite the context guides to use another example. Thanks!

**Comment by joepstender** [comment]
Great! Sorry for posting this again here, I now see it was already mentioned in #44 
I also would prefer to have User - Email (or Phone number...), and then add for example "Profile" refer to the User with all other stuff you'd want to add.
