### ISSUE TITLE
Wrong arity listed in descriptions for context tests

### ISSUE THREAD

**Issue by liamwhite** [aaronrenner/phx_gen_auth#59]
`get_user_by_email_and_password/1` (should be /2)
https://github.com/aaronrenner/phx_gen_auth/blob/3ed8ce9655ec07047445588808db028e5bfba01c/priv/templates/phx.gen.auth/context_functions.ex#L33
https://github.com/aaronrenner/phx_gen_auth/blob/3ed8ce9655ec07047445588808db028e5bfba01c/priv/templates/phx.gen.auth/test_cases.exs#L15

---

`get_user_by_reset_password_token/2` (should be /1)
https://github.com/aaronrenner/phx_gen_auth/blob/3ed8ce9655ec07047445588808db028e5bfba01c/priv/templates/phx.gen.auth/context_functions.ex#L311
https://github.com/aaronrenner/phx_gen_auth/blob/3ed8ce9655ec07047445588808db028e5bfba01c/priv/templates/phx.gen.auth/test_cases.exs#L405

---

`reset_user_password/3` (should be /2)
https://github.com/aaronrenner/phx_gen_auth/blob/3ed8ce9655ec07047445588808db028e5bfba01c/priv/templates/phx.gen.auth/context_functions.ex#L332
https://github.com/aaronrenner/phx_gen_auth/blob/3ed8ce9655ec07047445588808db028e5bfba01c/priv/templates/phx.gen.auth/test_cases.exs#L434

**Comment by aaronrenner** [comment]
@liamwhite Thanks for catching this! A PR would definitely be appreciated!
