### ISSUE TITLE
Invite-Only Applications (No public registration)

### ISSUE THREAD

**Issue by paulstatezny** [aaronrenner/phx_gen_auth#66]
Thanks so much for this library! Really great stuff. ❤️ 

I'm wondering, do you have any specific recommendations for modifying the generated code for an application that _doesn't_ have public registration? That is, an application where you set up "administrators" to start off, and then from that point on the way that users join is by invitation. This would be typical of an application used by a business, with only its employees as users.

Thanks!

**Comment by josevalim** [comment]
Hi @paulstatezny! Glad you are enjoying! My suggestion is to ask this question on the elixir forum in case someone has already tried an approach similar to the one you propose and can give you concrete pointers. :) Good luck!
