### ISSUE TITLE
Delete User function?

### ISSUE THREAD

**Issue by owenstrevor** [aaronrenner/phx_gen_auth#71]
I'm looking through the Accounts context and I don't see a function to delete the user.

I noticed the migration for the user_tokens table has cascade deletion on it, which is good, just want to make sure I'm not messing anything up by manually deleting users or writing my own simple function for this.

**Comment by josevalim** [comment]
There is no user function because deleting a user can become complex (and sometimes plain undesired) but if you are just starting out there should be no surprises. :)
