### ISSUE TITLE
[Suggestion] Add the 0.5.0 tag in git to the actual 0.5.0 release (f21ef29)

### ISSUE THREAD

**Issue by altdsoy** [aaronrenner/phx_gen_auth#88]
Hello all,

Usually I look in the tag tab of the branch select input to see the latest version of a package (of it not appears immediately elsewhere on the repo home page) or when I'm not looking in hex.pm.

Anyway it's good to see new release of the package.. :+1:

**Comment by aaronrenner** [comment]
Thanks for pointing this out! Looks like I had created it locally and forgotten to push it. 😅 

The `v0.5.0` tag has been pushed. 👍
